### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Globegitter** [sane/sane#9]
These are the immediate things on the todo list, roughly in order of priority:

**Immediate**
- [x] Add a --containerless or --docker flag, to have a quick&simple dev setup without docker
- [x] Implement `sane up/serve` command to start up both servers and have a unified log
- [x] See if you can improve stability and first time user experience (related to Docker IP story)
- [x] Improve the Docker IP story. Either automatically open the server in the browser, or print the IP, or automatically map to localhost. Might also be worth getting the Docker IP dynamically to prevent any possible conflicts.
- [x] Switch all the async stuff with ES6/ES7 syntax via [esnext](https://github.com/esnext/esnext)
- [ ] To save time with setting up sails dependencies think about symlinking that, similar to how sails does it on `sails new` command 

**Next**
- [ ] Sort out deployment with docker-gen using a nginx container
- [x] Redis support (probably with the ability to choose it in addition to another db)
- [x] Look into creating a generator for shared code, models to start with via `sane g resource <name>` 
- [x] Remove automatically initialized git by ember-cli. Think about initializing on sane level.
- [x] Look how to improve async exec calls, so `pleasent-progress` can be used without having to mess around with tons of callbacks. https://github.com/tj/co might be one solution.
- [ ] Think about adding an optional `--cors` flag or just add the necessary settings commented out (removes the need of the `--proxy` flag and especially useful if you are going to develop a cross-platform app)
- [x] Add a `--verbose` flag to show the original output
- [ ] Add a `--force` flag to carry on running a command even when there is an error
- [x] Look at https://github.com/feross/hostile to make your docker server available via localhost. (done via https://github.com/boot2docker/boot2docker/blob/master/doc/WORKAROUNDS.md#port-forwarding)
- [x] Add note on how to be able to develop on this project
- [x] Add more info and possible fixes for fig/docker to readme.
- [x] Find a better way to define project root and sane root. Look more into  `__dirname` as well as `process.cwd()`
- [ ] Check https://github.com/stefanpenner/ember-cli/blob/7868f9e26783932e28845a8e320b9197d7af5b5f/lib/utilities/ember-cli-version.js for version number stuff

**Nice to haves:**
- [x] Add some tests

**Done:**
- [x] Test all the different db connections
- [x] Test that `ember server --proxy` works
- [x] Investigate how to improve the output when ember-cli creates the project (i.e. not have all these bower and npm install messages show up)
- [x] Restructure the whole code to make it more readable and more easy to extend

**Notes:**
Once the first two todos are sorted out and tested, I might start pushing it as an official npm package.

`sane g resource <name>`  what should it be a proxy call for?
There is  `sails generate api <name>`, which doesn't allow attributes to be defined, so we could just call `sails generate model` followed by `controller` to add support for that. `ember g resource` allows attributes to be defined, so no problem there.
It would probably make sense to have some kind of `sane sync` that checks the models and makes sure they are matching each other.

Proper commands need to be spec'd out.

Get docker IP on Mac: `boot2docker ip`
To edit the host file (map Docker IP to localhost): https://github.com/feross/hostile

If anyone wants to contribute, just let me know.
